version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: live-collab-board-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: live_collab_board
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
    driver: local
