# Usa a imagem oficial do MongoDB
FROM mongo:6.0

# Define o diretório de trabalho dentro do contêiner
WORKDIR /data/db

# Expõe a porta padrão do MongoDB
EXPOSE 27017

# Comando para iniciar o MongoDB
CMD ["mongod"]
